<?php
/**
 * Created by PhpStorm.
 * User: Marta
 * Date: 01.01.2019
 * Time: 22:50
 */

namespace App\Form\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class ChangeDebtType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('zwiekszenieDlugu', NumberType::class, array(
                'label' => 'Dodaj kwotę do długu: ',
                'data' => 0
            ))
            ->add('zmniejszenieDlugu', NumberType::class, array(
                'label' => "Dodaj kwotę do spłaconych: ",
                'data' => 0
            ))
            ->add('akceptuj', SubmitType::class, array(
                'label' => 'ZAPISZ ZMIANY'
            ));
    }

}