<?php
/**
 * Created by PhpStorm.
 * User: Marta
 * Date: 02.01.2019
 * Time: 23:02
 */

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class ChangePasswordType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('stareHaslo', PasswordType::class, array(
                "label" => "Wpisz aktualne hasło:"
            ))
            ->add('hasloUzytkownika', RepeatedType::class, [
                'type' => PasswordType::class,
                'constraints' => [
                    new NotBlank(),
                    new Length([
                        'min' => 5,
                        'max' => BCryptPasswordEncoder::MAX_PASSWORD_LENGTH,
                    ]),
                ],
                'first_options' => [
                    'label' => 'Wprowadź nowe hasło',
                ],
                'second_options' => [
                    'label' => 'Potwierdź nowe hasło',
                ],
            ])
            ->add("akceptuj", SubmitType::class, array(
                "label" => "ZMIEŃ"
            ));
    }

}