<?php
/**
 * Created by PhpStorm.
 * User: Marta
 * Date: 03.01.2019
 * Time: 11:53
 */

namespace App\Form\Type;


use App\Entity\Permissions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class ChangePermissionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add("checkbox", PermissionsType::class, array(
                "label" => "Zmień uprawnienia pracownika:",
                "data_class" => Permissions::class
            ))
            ->add("akceptuj", SubmitType::class, array(
                "label" => "ZAPISZ ZMIANY"
            ));
    }

}