<?php
/**
 * Created by PhpStorm.
 * User: Marta
 * Date: 13.12.2018
 * Time: 12:27
 */

namespace App\Form\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class PhotosType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('zdjecie', FileType::class, array(
                'label' => 'Wybierz zdjecie'
            ))
            ->add('dodaj', SubmitType::class, array(
                'label' => "zapisz"
            ));
    }
}